# Generated by Django 5.2.7 on 2025-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото')),
                ('problem_type', models.CharField(choices=[('infrastructure', 'Инфраструктура'), ('safety', 'Безопасность'), ('beautification', 'Благоустройство'), ('social', 'Социальное'), ('other', 'Другое')], max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Решена'), ('rejected', 'Отклонена')], max_length=50)),
            ],
        ),
    ]
