# Generated by Django 5.2.7 on 2025-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_problem_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='problem',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес обьекта'),
        ),
    ]
